### ISSUE TITLE
Error while i click on Play

### ISSUE THREAD

**Issue by TVGames** [SkyrimTogether/issues-game#286] opened 2019-05-21 20:59 UTC
![image](https://user-images.githubusercontent.com/8538669/58130291-13713880-7bf2-11e9-859f-bd6c00069c12.png)

Whenever i try to start game from Harbor, it keeps launching this error to me
anyone can help me?

**Comment by Neusor** [comment] 2019-05-21 21:20
You get these errors when you're running an older version of the game or an pirated version. 

These errors are created when Skyrim Together hooks into the memory addresses, but they don't line up with the known memory address paterns.

We only support the latest steam version of Skyrim.

**Comment by matroyy** [comment] 2019-05-21 21:42
I got this error too but I buy the game on steam, I even try to clean install many time

**Comment by ZeroKaion** [comment] 2019-05-22 08:18
I fixed this error for my friend when I told him to deactivate CBP Physic and Immersive Citizen if you are using mods.

**Comment by Pokang** [comment] 2019-06-06 08:53
This error is caused by mods that modify the base exe file of the game, or non-official versions of Skyrim which we don't support at all.
Removing the said mods or playing on the legal version will 100% fix it.
If it doesn't, make a clean install of the game and it will be fixed.
Closing since this is working as intended.

**Closed by Pokang** 2019-06-06 08:53 UTC
