### ISSUE TITLE
Keeps Saying Game Not Found 

### ISSUE THREAD

**Issue by ARBITOR117** [SkyrimTogether/issues-game#256] opened 2019-02-13 19:18 UTC
## Description
I start the client and sign in, then it immediately says game is not found. And i have both the game and file saved on the same disk. i tried to uninstall both the game and client. Also, deleted the mod files that it leaves behind when uninstalled. Idk why it keeps happening. Been trying to fix this issue on my own for over 2 hours. 
![2019-02-13 14-03-15_moment](https://user-images.githubusercontent.com/47609472/52737385-34deda80-2f9a-11e9-98ea-2b7f59e42e5d.jpg)

## Reproduction rate
Every time
How many times can you reproduce it?
Every time
## Expected result

Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    
    
 * Operating system (choose one):
  * Windows 10 x64

## Final checks for the reporter

- [X] I have browsed through the other issues and confirmed that this issue has not been reported already
- [X] I made sure that I have applied the template for my bug report

**Comment by SteamDosh** [comment] 2019-02-13 19:26
duplicate of https://github.com/SkyrimTogether/issues-launcher/issues/8

**Closed by SteamDosh** 2019-02-13 19:26 UTC
