### ISSUE TITLE
Best way to implement Quest Synchronization

### ISSUE THREAD

**Issue by MrCoby220** [SkyrimTogether/issues-game#191] opened 2019-01-31 19:21 UTC
## Description

Each player would have a quest order which is a list of all the quest they currently have and what stage they are at in that quest, a player could invite other players to what is called a quest party once other players join his quest party it would unload all there quest and load the host's quest order, if a player that is in the quest party complete a quest with the other player and that quest his in his original quest order it would complete it for him if not it would do nothing, when a player save his game it would unload the host's quest order and reload his original quest order (making sure that it saves similar quest stages and completion) the quest host is different than cell host and party host.

**Comment by MrCoby220** [comment] 2019-01-31 20:17
Additionally players that are in a quest party could have a book icon next to there name

**Comment by storm1er** [comment] 2019-01-31 21:53
Duplicate of #49

**Comment by MrCoby220** [comment] 2019-01-31 22:07
storm1er i would not call it a duplicate just an idea / suggestion after all im not a dev and the dec will do it the way they think is the best

**Comment by storm1er** [comment] 2019-02-01 09:13
@MrCoby220 

As you can see on #49, @Evayr said

> Synchronize the quests to all players, **but first of all we need to decide how we will sync them.** Will we choose a host and if Player 1 (the host) has quest X completed but Player 2 (the player) doesn't will we mark it as complete for Player 2 (@yamashi, @Evayr, @SteamDosh)?

This is the same as you said: "_just an idea/suggestion_"

I'm not judging or anything, as you said, you're not a developer, 
You just need to understand that splitting possible answer for any problem based on "I'm a dev or not" is not how GitHub works ;)

Take a look at [#49#issuecomment-457933710](https://github.com/SkyrimTogether/issues-game/issues/49#issuecomment-457933710): I'm a developer but not on this project, but my suggestion is in the thread they talk about it.

It's way easier for them to look at the same thread than searching for every thread which talks about it, even if they have to skip some answers.

**Comment by SteamDosh** [comment] 2019-02-01 09:18
duplicate of #49

**Closed by SteamDosh** 2019-02-01 09:18 UTC
