### ISSUE TITLE
Task sharing

### ISSUE THREAD

**Issue by zxyxz** [SkyrimTogether/issues-game#340] opened 2019-09-17 08:16 UTC
## Description

Task sharing

1. Share a task with a designated player
2. Synchronized task completion status

This avoids multiple player task bugs,
I think it can be done through the console.

**Comment by Pokang** [comment] 2019-09-17 09:08
Incredibly unclear post and complete deletion of the template... 
Closing the issue.

**Comment by Neusor** [comment] 2019-09-17 09:09
This is not a bug, but an not yet implemented feature aka Quest Sync.

**Closed by Pokang** 2019-09-17 09:08 UTC
