### ISSUE TITLE
Yngol Barrow crashes

### ISSUE THREAD

**Issue by Sekoshiba** [SkyrimTogether/issues-game#185] opened 2019-01-30 20:41 UTC
## Description

Mod works fine with no issues or desync, until entering the area "Yngol Barrow". Upon entering, desync skyrocketed for myself and another player, then we crashed. There's an orb of light at the start of the cell that tries to pursue the player, which might be related(?).

Related formIDs|
---------------|
Unsure-- Sorry!

## Steps to reproduce

How to reproduce this issue:

1. Join a party.
2. Enter Yngol Barrow.
3. Proceed to the orb of light.
4. Crash.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

No .dmp file located at <Skyrim_Directory>/Data/Online :(

## Reproduction rate

Reproduced twice ingame.

## Expected result

Expected result of above steps would be continued gameplay. What actually happened was the crash. (Sorry, not sure if that's a helpful description).

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Can't, due to crashing. Desync involved invisible players, naked players, and ended with both games crashing.

**Comment by Sekoshiba** [comment] 2019-01-30 20:51
Additionally managed to reproduce this issue by merely looking at an entrance to the cell. Very bizarre.

**Comment by f13rce** [comment] 2019-01-30 20:54
Will have a look with the latest changes in our codebase. Will close this issue if I cannot reproduce this.

**Comment by f13rce** [comment] 2019-01-30 20:57
![489830_20190130215730_1](https://user-images.githubusercontent.com/39367107/52012121-0d880800-24da-11e9-8c65-6e8a6ad9bb26.png)

This orb?

**Comment by f13rce** [comment] 2019-01-30 21:03
Just cleared the cave, didn't seem to crash so I'll close it for now. Reopen it if you can reproduce this after the upcoming update (with preferably a different save). :)

![489830_20190130220219_1](https://user-images.githubusercontent.com/39367107/52012418-cd755500-24da-11e9-8b95-d8c085300256.png)

**Closed by f13rce** 2019-01-30 21:03 UTC
Labels: comp: client, type: crash
