### ISSUE TITLE
Crashing on cell change, or save. Only one specific character that was being used.

### ISSUE THREAD

**Issue by theknifekitty** [SkyrimTogether/issues-game#175] opened 2019-01-29 19:30 UTC
## Description

Was running through Bleak Falls with party of 3. Was knocked down, but health bar remained. When I was revived, i wasn't able to attack or jump. After disconnecting, I crashed. Have been unable to connect to other players, or change cells, as both lead to a crash.

## Steps to reproduce

1. Get knocked down.
2. If health bar persists on bottom, then attacked again.
3. Get revived
4. Possiblity to be unable to jump or attack.

## Reproduction rate

Has happened seldomly when crashing while connected, but those instances are suually solved by logging out of Harbor, then signing back in. This however doesn't work, and the entire characters file is borked.

## Your environment

The Elder Scrolls V: Skyrim Special Edition

**Comment by ButtonSmasher** [comment] 2019-01-29 19:47
Go back to an older save.. If you crash in a cell with someone or for any reason just reload back. That fixes it

**Comment by ButtonSmasher** [comment] 2019-01-29 20:22
Sorry to say, but i think your character is a corrupted savefile. Otherwise try disconnecting enter the cell then reconnect if you don't crash. Save try again.

Otherwise start a new character

**Comment by f13rce** [comment] 2019-01-30 01:05
Might be a duplicate of https://github.com/SkyrimTogether/issues-game/issues/172 and https://github.com/SkyrimTogether/issues-game/issues/155 . Will close this for now as the fix will come in soon.

**Closed by f13rce** 2019-01-30 01:05 UTC
