### ISSUE TITLE
Crash on save.

### ISSUE THREAD

**Issue by paden2002** [SkyrimTogether/issues-game#331] opened 2019-09-07 00:08 UTC
## Description
The game crashes every time I save after entering a cell with another player in it regardless of what I do. I have tried disconnecting and moving cells and from what I can tell no matter what you do after being in the same cell as another player it crashes when you save. I've also attempted deleting my server and letting the integrity check replace it to no effect.

Related formIDs|
N/A

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Be at any point present in a cell with another player
4. Save.
5. Crash.

(i put the dmp in a zip because it wouldnt let me send it normally) [dmp for git issue.zip](https://github.com/SkyrimTogether/issues-game/files/3586060/dmp.for.git.issue.zip)

## Reproduction rate

Every time I've tried so far (about 8 times).

## Expected result

A crash.

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 7 x64

## Final checks for the reporter

- [yep did this ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [more or less ] I made sure that I have applied the template for my bug report

**Comment by syrous137** [comment] 2019-09-07 01:34
Having the same issue. Also notice the game crashes when both players enter the same area the game tries to auto save and crash.

**Comment by Pokang** [comment] 2019-09-22 09:06
This should have been fixed with latest patches, please try again on a fresh save and feel free to reopen if it still happens, because we cannot seem to reproduce it.

**Closed by Pokang** 2019-09-22 09:06 UTC
