### ISSUE TITLE
Door to quest location disappeared

### ISSUE THREAD

**Issue by FvtHek** [SkyrimTogether/issues-game#328] opened 2019-08-11 21:34 UTC
## Description

Im playing with 1 other person. When doing quests sometimes doors to quest locations will disappear. The actual door is gone and i can only see the black void textures that is behind it. Door is not invisible as i can not interact with anything where the door should be.

When using the door from the inside the game will either teleport me to the same place where i'm using the door (just rotated 180 degrees as if i just entered the cell), or teleport me to a place outside the map. 

This has happened to me with 3 characters. 2 times with mods, 1 time without mods on a fresh install of the game. The places where this happened were twice at the College of Winterhold with the door to The Hall of the Elements while doing "The Eye of Magnus" quest. And once with the door the The Winking Skeever in Solitude while doing the "Scoundrel's Folly" quest.

I'm not sure how it happens and also unable to reproduce it.

Related formIDs|
---------------|
[Hall of the Elements - WinterholdCollegeHallofTheElements](https://en.uesp.net/wiki/Skyrim:Hall_of_the_Elements)|
[The Eye of Magnus - MG08](https://en.uesp.net/wiki/Skyrim:The_Eye_of_Magnus)|
[The Winking Skeever - SolitudeWinkingSkeever](https://en.uesp.net/wiki/Skyrim:The_Winking_Skeever)|
[Scoundrel's Folly - TG04](https://en.uesp.net/wiki/Skyrim:Scoundrel%27s_Folly)|

## Steps to reproduce

How to reproduce this issue:

I was unable to reproduce the issue where the door itself disappeares, but once the door is gone it doesnt come back unless you reload an older save.

## Reproduction rate

How many times can you reproduce it?

I reproduced it on accident 3 different times with 3 different characters. Twice with mods, once with a fresh install of SSE without any mods except for ST.

## Expected result

Door to quest location is gone and waypoint to the location points to a random location on the map. When i use the same door from the inside the game with either send me to the location i am already at but rotate my character 180 degrees (as if i just entered the location), or teleport me to a location outside the map.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 8.1 Pro x64
    
  

## Evidence (optional)

I will include 3 screenshots from my game of my last character where this issue occured.

This is where the door to The Winking Skeever should have been.
![ScreenShot0](https://user-images.githubusercontent.com/22367273/62839774-9bb22780-bc8f-11e9-9e8f-75885c61b20c.png)

This is where the quest marker points to on the map
![ScreenShot1](https://user-images.githubusercontent.com/22367273/62839775-9bb22780-bc8f-11e9-8184-7824a1315504.png)

And this is where i end up when i use console commands to teleport into The Winking Skeever and use the door to get outside.
![ScreenShot2](https://user-images.githubusercontent.com/22367273/62839776-9c4abe00-bc8f-11e9-8077-fab7b9655ea0.png)

These 3 screenshots where from when i was doing the Thieves Guild quest "Scoundrel's Folly" right after i got the Firebrand Wine.

## Final checks for the reporter

- [ x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ x] I made sure that I have applied the template for my bug report

**Comment by matroyy** [comment] 2019-08-17 16:34
I almost the same problem but the door just move location it and was underground and my arrow was showing it in to the ground

**Comment by danielkillsya2** [comment] 2019-08-17 16:38
For me, 2 doors in winterhold were replaced with ones that went to a giant camp near whiterun.

**Comment by moonlightluna-kd** [comment] 2019-08-26 12:53
i had the same issue. we found anytime, we entered a door simultaneously it would make the door disappear pr delete it completely.

**Comment by LPkkjHD** [comment] 2019-09-04 22:12
Experienced the same behavior. After entering the Bards College multiple NPCs and players try to leave the building (including me).
## Expected behavior
Door gets me to Skyrim(Solitude)
## Actual behavior
- Door teleports me - after a loading screen - back into the Bards College
- Door is inaccessible from the outside (Solitude)
## Pictures
![alt text](https://steamuserimages-a.akamaihd.net/ugc/781860008170275998/91F8197617D2FD84EC263EF326CF8DCA564E2C8E/)
![alt text](https://steamuserimages-a.akamaihd.net/ugc/781860008170275388/72C4C5019525CB8AAFB5B922BAD5A82BACE70040/)

**Comment by tyler-reclen** [comment] 2019-09-11 21:56
here's what i found

sometimes when (player 1)  tries to enter a cell where (player 2) already is: the door "breaks".

when the door "breaks" the following happens:
* activating the door teleports the player to an arbitrary place in the same cell
* This place is often out of bounds and for a given door is always the same spot, I assume (0,0,0)
* using coc to get to the Otherside of the door: graphically, the door is gone, and there is no way through  
* the problem only affects player 1. 
* player 2 can use the door as normal

I am not sure what causes the door to break but it only happens when entering a cell where there is another player and seems to happen when we have been connecting and disconnecting to fix players being invisible to each other.

Skyrim Special Edition
Windows 10 x64

**Comment by nathanh2011** [comment] 2019-09-22 07:32
My friend and I are getting this exact same issue, both of us got it in the College of Winterhold. I originally 'lost' the door to the hall of elements which required me to load a previous save from when I was level 2 and work it back up. 

On getting my character back to the point where I was, I could get back into the hall of elements and everything seemed fine, then my friend lost the door to the arch mages quarters.

We have not been able to find a fix for this apart from using the 'coc' console command. Any help with this issue would be greatly appreciated.

**Comment by Pokang** [comment] 2019-09-22 09:10
This is a duplicate of #337 , which we're still trying to reproduce internally, with no success so far.
Please add comments on #337 if needed.

**Closed by Pokang** 2019-09-22 09:10 UTC
