### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by Asmodiu** [SkyrimTogether/issues-game#110] opened 2019-01-26 11:22 UTC
## Description
Two players server, both use Win7.
I am crashing constantly, my friend is not (regadless who is hosting).
Crashing caused by taking items, reading books.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server or invite friend.
3. Take item/use object.
4. Crash.

## Reproduction rate

Very often, probability to occur 70-80% of perfoming actions.

## Expected result

Crash to desktop.

[20190126-175658-6628-10224_dump.zip](https://github.com/SkyrimTogether/issues-game/files/2798925/20190126-175658-6628-10224_dump.zip)

## Your environment

Windows 7
The Elder Scrolls V: Skyrim Special Edition (Steam)

## Evidence (optional)

None.

**Comment by Pokang** [comment] 2019-01-27 04:55
This issue is caused by Windows 7, we're not sure why but we can definitely hand out a fix in the meantime, which you can find here : https://www.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/
Closing the issue since that will most likely resolve your issue as it did for every other Windows 7 user, don't hesitate to contact us on Discord if you're still having this problem.

**Closed by Pokang** 2019-01-27 04:55 UTC
