### ISSUE TITLE
Can't see another player because of localization

### ISSUE THREAD

**Issue by KickerMix** [SkyrimTogether/issues-game#109] opened 2019-01-26 10:32 UTC
## Description

If you playing with someone, who use different localization, you can't see each other. If you try /tp to him, you'll get message that your friend in different cells.
In Eng localization console says:
  *PLAYERNAME has entered Skyrim
but in Rus console says: 
  *PLAYERNAME has entered Скайрим

## Steps to reproduce

How to reproduce this issue:

1. Start the game with a friend on different language (For me it was English and Russian).
2. Connect to each other.
3. Start party.
4. You can't see your teammate in game

## Reproduction rate

100%

## Expected result

See your party member like it should be

## Your environment

     The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

![20190126143505_1](https://user-images.githubusercontent.com/27219313/51785338-3164ea00-2178-11e9-8d69-43e4fe149a24.jpg)

**Comment by StrongCrocodile** [comment] 2019-01-27 02:31
As one would imagine, the same thing happens between English and French. Cell names are different and you can't see the other players.

**Comment by Pokang** [comment] 2019-01-27 04:56
That has been fixed in an internal patched that will be deployed in the next few days, thank you very much for your report.
Will close the issue when the patch will be pushed to the live version.

**Comment by Dumbeldor** [comment] 2019-01-27 18:08
I developed a patch last night to use cellId instead of cellName. But the problem is that cellid is an small grid within a cell.

So here's the result when a person runs into a cell : 

![image](https://user-images.githubusercontent.com/3883583/51804913-d3630000-2266-11e9-9666-b0cca5519735.png)

We are thinking about a better way to proceed. We'll keep you informed.

Thank you for this issue.

**Comment by theo-ardouin** [comment] 2019-05-18 19:54
Hi, any update on the issue ?
Just stumbled upon it now, currently re-installing my game because internally, even when changing the game language, the name of the cells is kept, it seems :(

**Comment by Dumbeldor** [comment] 2019-05-25 13:00
Hi @theo-ardouin 

We forgot to merge the fix. Now it's fine since the last version of the nighty !

Thanks for your message,
Have fun !

**Closed by Dumbeldor** 2019-05-25 13:00 UTC
Labels: type: bug, type: feature
