### ISSUE TITLE
When another player is a werewolf, others see him as a naked stretched out player.

### ISSUE THREAD

**Issue by TheGhostlyDude11** [SkyrimTogether/issues-game#320] opened 2019-07-12 03:19 UTC
No werewolf body.

When another player turns into a werewolf, you see them as a stretched out naked player and not a werewolf.

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

Have someone turn into a werewolf, then look at them.

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Someone turns into a werewolf
4. Others see him as a stretched, naked player.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

Every time someone turns into a werewolf.

## Expected result

The werewolf appears normal.

## Your environment
Anywhere
* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    
 * Operating system (choose one):
    * Windows 10 x64

## Final checks for the reporter
3
- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
Yes.
- [ ] I made sure that I have applied the template for my bug report
Yes.

**Comment by Pokang** [comment] 2019-09-22 09:20
Duplicate of #61 .

**Closed by Pokang** 2019-09-22 09:20 UTC
