### ISSUE TITLE
Launcher/Steam Error: Allow Game Launch? SSE is attempting to launch with the optional parameters shown below -

### ISSUE THREAD

**Issue by MJLgaming** [SkyrimTogether/issues-game#261] opened 2019-02-19 01:28 UTC
I bought my friend Skyrim Special edition and we both are patrons. The picture shown below happens whenever he tries too play as well as the UI in game isn't there and debug console does nothing. It uses base game launcher for some reason and brings up this error. Also someone said "This is what happens when you launch ST without having Steam opened beforehand or when you have weird Windows perms.
In the latter case, start our launcher as admin." This did not work.
---------------

## Steps to reproduce

How to reproduce this issue:

1.Download SSE
2. Download Harbor Launcher
3. Link account
4. Install and run Launcher
5. Debug console dosen't write anything
6. The Steam message pops up and if you hit OK the base game launcher pops up as well.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

(I can't get that from him but in this case seeing as we can't get the game to even launch and work corectly I don't think this is needed)

## Reproduction rate

It happens to my friend every time but it seems like something no one else can reproduce, I don't know why. No one else has had this issue it seems.

## Expected result

?

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Final checks for the reporter

- [Y] I have browsed through the other issues and confirmed that this issue has not been reported already
- [Y] I made sure that I have applied the template for my bug report

**Comment by MJLgaming** [comment] 2019-02-19 01:30
ClosedDEFIANCE is his Skyrim Together name btw. We have tried fresh installs altering perms running everything in admin etc.

**Comment by Pokang** [comment] 2019-02-19 01:45
Edited your issue to exclude the screenshot since you just shared your connection token publicly.
Tell your friend to tag me on our Discord server @Pokang#7174, thank you!

**Comment by MJLgaming** [comment] 2019-02-19 01:50
If the connection token is the garbly stuff before hand that changes every time

**Comment by MJLgaming** [comment] 2019-02-19 01:51
Also he is frustrated that it isn't working and has given up so it's just up to me to deal with but if there are any questions I can probably answer them

**Comment by MJLgaming** [comment] 2019-02-19 01:52
Should i add the picture back and censor the numbers?

**Comment by Pokang** [comment] 2019-02-19 01:55
No, we've seen it a few times, we know what this is, it's just steam asking if the game is allowed to run with special parameters. Try pressing "OK" once on that box, closing the SSE launcher that it will open, and then relaunching the mod.
I am not willing to troubleshoot your friends issue here through GitHub and also through you, please reach out to me on Discord if you're asking for support. Since that issue only happens to one person and we will never be able to reproduce it, I'm closing the issue.

**Closed by Pokang** 2019-02-19 01:55 UTC
