### ISSUE TITLE
autosave

### ISSUE THREAD

**Issue by xxcandycakesxx** [SkyrimTogether/issues-game#279] opened 2019-05-18 21:28 UTC
## Description

I can not save, quicksave and autosave does not work aswel not in any case

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. try to do a save/quicksave/autosave

## Reproduction rate

always

## Expected result

being able to play and continu later

## Your environment

* Game edition:
    * The Elder Scrolls V: Skyrim
    
 * Operating system:

    * Windows 10 x64

## Final checks for the reporter

- [ ] I made sure that I have applied the template for my bug report
- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already

**Comment by WopsS** [comment] 2019-05-18 23:25
Duplicate of #278.

**Closed by WopsS** 2019-05-18 23:25 UTC
