### ISSUE TITLE
Player Summons will cause gravestone to dissapear if they kill another player

### ISSUE THREAD

**Issue by Erithionis** [SkyrimTogether/issues-game#165] opened 2019-01-28 20:46 UTC
## Description

A player summoned a fire atronach and it became hostile to another player. When the player died their gravestone dissapeared when the summoner player approoached it. The dead player could not move when they typed /respawn and simply ran in place.

Related formIDs|
---------------|
[Fire Atronach- 00023AA6](https://elderscrolls.fandom.com/wiki/Flame_Atronach_(Skyrim))|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Summon a flame atronach
4. Have a player attack it
5. Let it kill the player
6. Apprach the gravsestone
7. Have the dead player type /respawn

## Reproduction rate

Has so far occurred once, 100% of the time

## Expected result

Gravestone does not dissapear, player can move upon /respawn

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by f13rce** [comment] 2019-01-29 10:45
Interesting.. Will have a look. Seeing how this has happened only once I'll look for some more possibilities on why this would happen.

**Comment by f13rce** [comment] 2019-01-29 15:26
Cannot reproduce this.
![489830_20190129162557_1](https://user-images.githubusercontent.com/39367107/51918893-a76c8980-23e2-11e9-98db-ce71fe8fdaf7.png)

Will try to see if there's anything else I can do for the gravestone.

**Comment by f13rce** [comment] 2019-01-29 15:31
The gravestones should be persistent according to the code I'm looking at. I don't think I can do much more, so I'll close this issue for now. Please re-open it if it occurs, preferably with a video if possible.

**Closed by f13rce** 2019-01-29 15:31 UTC
Labels: cannotreproduce, comp: client, type: bug
