### ISSUE TITLE
Some bugs we found during the week of the game.

### ISSUE THREAD

**Issue by BLADEkuzia** [SkyrimTogether/issues-game#330] opened 2019-08-21 13:36 UTC
First, I want to say thank you for the work done by all who participate in the project. You have realized the dream of many, my girlfriend and I have long dreamed of a cooperative in Skyrim. Thank you very much from your Russian fans!

The first bug with which we are faced, there are more than once described:
I play on a steam license special edition. There are no problems with creating and connecting to the server.  But my girlfriend is not licensed and we have downloaded a pirated version of it. And there was an earlier version, and she couldn't not join her server, not mine. The game is immediately crashed after entering the IP address. (if anyone is experiencing the same problem, and I've seen a lot of such requests, check if you have the latest version of the game)

The second problem, also described but a little differently than we have.  We decided to go all out and started installing mods.  Yes, not the smartest idea, given that the developers have repeatedly said that it is better not to play with mods. But we are risk-takers. Live a different life, armor, graphics, worked fine on test characters. But then we created new ones. And my girlfriend started to crashed again when trying to join the server. BUT last time the server just wrote that it Disconnected without any errors. And now wrote an error "npc_is_null". After a brief reflection, what has changed from the test, I realized that this time she did not play the Imperial, and the mod that we have not experienced a custom race. I repeated her actions and created this race, I had the exact same problem (the funny thing is that when I created the race, not leaving a server was no problem but as you tried to reconnected to the server, the game immediately crashed.
we removed the custom race and now play on standard races with CBBE

The third bug we are still facing. 
Sometimes after frequent teleports, changing locations, load saves. One of us will no longer see the second, and the second sees the first goes without animation, enemies start to either disappear or be duplicated by one of the two, and ignore the second.  The problem was solved by restarting the server and restarting the game. But still continues to appear.

The fourth bug: 
In the FAQ I read that you can transfer items to each other using chests or just throw on the ground. 
We have some reason, the chests are not synchronized items they are always different, as the objects in the enemies. We do not see what we leave in them, and the earth does not appear objects that we throw away. Sometimes not synced enemies, sometimes I see 4 opponents and she's 3, or I see the enemy and she is not, and Vice versa. And in many cities duplicated their guards became twice as many, and enemies in some places.

The fifth bug:
This bug I do not think that is caused by Skyrim Thoether Since it also I have in Fallout 4 I thought it was because of the abundance of mods (200+ wrong organization and a lot of not updated, and tied to f4se) 

And here we have installed no more than 40 and do not use skse. But the bug appears nevertheless. What is the point, sometimes after a long game, the game suddenly crashed, and after starting the last save, after trying to save in any way the game crashed, the problem is solved by searching for a save that does not have this bug, but sometimes it is a waste of several hours of progress.

Sixth bug: 

Also indirectly refers to Skyrim together, but still arise only in it.
We have installed the Dowakin Relax mod, but when playing the animation the second player does not see them.

And the latter is not a bug but a question.

Is it possible to play Skyrim together using skse? And if Yes how to start it through skse I did not find anywhere as to specify in the client a path to the file of start.

That's all for now, sorry for the improper execution, and I sent it without logs, but I just wanted to write about bugs that I found when using.  

Thanks again to everyone who is working on the project you are the best of the best!

**Comment by Dragonisser** [comment] 2019-08-21 15:55
We dont support pirated versions

**Comment by Pokang** [comment] 2019-08-21 17:43
You're not using the provided template, and playing on a pirated version of the game, you're also saying that most issues are caused by other mods... 
I have trouble understanding what you want us to do there.
Closing the issue.

**Closed by Pokang** 2019-08-21 17:43 UTC
