### ISSUE TITLE
Feature Request: Notification of starting/joining session

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#78] opened 2018-11-14 23:19 UTC
## Description

Something added to the chat that just notifies you that you are in fact joining a session/server/game. Currently it doesn't say anything or make any notification, kinda looks like it isn't doing anything.

**Comment by SteamDosh** [comment] 2018-11-14 23:22
Duplicate of #25

**Closed by SteamDosh** 2018-11-14 23:22 UTC
