### ISSUE TITLE
Auto Correct disable

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#26] opened 2018-01-20 18:20 UTC
## Description

Automatic filling and correction of form controls is enabled.

## Actual result

When the user types into specific form fields, the browser suggests previously entered values.

## Expected result

The browser's suggestions should not appear.

**Comment by Dumbeldor** [comment] 2018-11-13 15:56
Not reproduced on the search field and on the connection to an server with an IP.
I think the problem is solved and we can close this issue.

**Comment by Gamepaw** [comment] 2018-11-13 16:05
Reproduced. May be only close spelling mistakes are detected or based on Default Language.
English - 'Chiar' instead of 'Chair' caused a red line in text chat and in search box, however not on IP.

**Comment by Dumbeldor** [comment] 2018-11-13 20:49
Fixed on my branch ui_groups_fix.
Waiting for the merge of my branch on rework to close the issue.

**Comment by Dumbeldor** [comment] 2019-02-16 22:32
i fixed that, so i close ;)

**Closed by Dumbeldor** 2019-02-16 22:32 UTC
Labels: comp: ui, type: bug
