### ISSUE TITLE
Conjuring causes crash leading to a windows blue screen error causing pc to restart.

### ISSUE THREAD

**Issue by Paraloxgaming** [SkyrimTogether/issues-game#231] opened 2019-02-07 21:51 UTC
## Description

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. summon flame atronarch
4.crash
5.windows blue screen

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.
[5e681de6-6b76-472f-b8f9-6fecabfb00fe.zip](https://github.com/SkyrimTogether/issues-game/files/2842791/5e681de6-6b76-472f-b8f9-6fecabfb00fe.zip)

## Reproduction rate

How many times can you reproduce it?
once
## Expected result

Describe your expected result.

## Your environment
White run with other player being cell host

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

**Comment by f13rce** [comment] 2019-02-07 22:26
![489830_20190207232456_1](https://user-images.githubusercontent.com/39367107/52446881-94b72a80-2b2f-11e9-8738-43a07218c959.png)

Yeah I cannot reproduce that one. Maybe verify if your divers/SkyrimSE is proper and isn't using mods or outdated drivers that could cause this. Closing this issue, but please reopen it if you can find a way to reproduce it.

**Closed by f13rce** 2019-02-07 22:26 UTC
